#!/usr/bin/env python3
"""
Example demonstrating the Interactive SRS Generation API.

This script shows how to programmatically use the interactive agent
to generate an SRS document through a conversational flow.
"""

import requests
import json
import time

# Configuration
BASE_URL = "http://localhost:5000/api/v1"


def print_separator():
    """Print a visual separator."""
    print("\n" + "=" * 80 + "\n")


def start_interactive_session():
    """Start a new interactive session."""
    print("🚀 Starting interactive SRS generation session...")
    response = requests.post(f"{BASE_URL}/interactive/start")
    
    if response.status_code == 200:
        data = response.json()
        print(f"\n✅ Session started successfully!")
        print(f"Session ID: {data['session_id']}")
        print(f"\n🤖 Agent says:\n{data['message']}")
        print(f"\n📊 Progress: {data['progress']['percentage']}%")
        return data['session_id']
    else:
        print(f"❌ Error: {response.json()}")
        return None


def send_message(session_id, message):
    """Send a message to the agent."""
    print(f"\n💬 You: {message}")
    
    response = requests.post(
        f"{BASE_URL}/interactive/respond",
        json={"session_id": session_id, "message": message}
    )
    
    if response.status_code == 200:
        data = response.json()
        print(f"\n🤖 Agent: {data['message']}")
        print(f"\n📊 Progress: {data['progress']['percentage']}%")
        
        if data['status'] == 'complete':
            print("\n🎉 SRS generation complete!")
            return data
        return data
    else:
        print(f"❌ Error: {response.json()}")
        return None


def save_srs_document(sections, filename="example_srs.md"):
    """Save the generated SRS to a file."""
    print(f"\n💾 Saving SRS document to {filename}...")
    
    markdown = "# Software Requirements Specification\n\n"
    markdown += f"*Generated on: {time.strftime('%Y-%m-%d')}*\n\n"
    markdown += "---\n\n"
    
    if 'introduction' in sections:
        markdown += "## 1. Introduction\n\n"
        markdown += sections['introduction'] + "\n\n"
    
    if 'system_description' in sections:
        markdown += "## 2. System Description\n\n"
        markdown += sections['system_description'] + "\n\n"
    
    if 'functional_requirements' in sections:
        markdown += "## 3. Functional Requirements\n\n"
        markdown += sections['functional_requirements'] + "\n\n"
    
    if 'non_functional_requirements' in sections:
        markdown += "## 4. Non-Functional Requirements\n\n"
        markdown += sections['non_functional_requirements'] + "\n\n"
    
    if 'user_interface' in sections:
        markdown += "## 5. User Interface Requirements\n\n"
        markdown += sections['user_interface'] + "\n\n"
    
    if 'constraints' in sections:
        markdown += "## 6. System Constraints\n\n"
        markdown += sections['constraints'] + "\n\n"
    
    markdown += "---\n\n"
    markdown += "*Generated by Interactive SRS Generator*\n"
    
    with open(filename, 'w') as f:
        f.write(markdown)
    
    print(f"✅ Document saved successfully!")


def main():
    """Run the interactive example."""
    print_separator()
    print("🎯 Interactive SRS Generation Example")
    print_separator()
    
    # Start session
    session_id = start_interactive_session()
    if not session_id:
        return
    
    print_separator()
    
    # Example conversation flow
    responses = [
        "I'm building a mobile fitness tracking app called FitTrack. It helps users "
        "maintain workout routines and track progress. The primary users are fitness "
        "enthusiasts aged 18-45.",
        
        "The main features include workout logging with exercise types and reps, "
        "calorie tracking with food database integration, progress visualization with "
        "charts and graphs, goal setting and reminders, and social sharing capabilities.",
        
        "Performance requirements: the app must load in under 2 seconds, handle 10,000 "
        "concurrent users, and work offline with sync when connected. Security: user "
        "data must be encrypted, secure authentication with OAuth2, and GDPR compliant "
        "data handling. Reliability: 99.9% uptime with automated backups.",
        
        "The app will run on iOS and Android with native look and feel for each platform. "
        "It needs a clean, minimal interface inspired by Strava and MyFitnessPal. Must "
        "support accessibility features including voice-over and high contrast mode.",
        
        "Technical constraints: must use React Native for cross-platform development, "
        "Firebase for backend services, integrate with Apple Health and Google Fit, "
        "and deploy through standard app stores. Must comply with health data regulations.",
    ]
    
    # Send each response
    result = None
    for i, message in enumerate(responses, 1):
        print(f"\n📝 Response {i}/{len(responses)}")
        result = send_message(session_id, message)
        print_separator()
        
        if result and result.get('status') == 'complete':
            break
        
        # Small delay for readability
        time.sleep(0.5)
    
    # Save the document
    if result and 'sections' in result:
        save_srs_document(result['sections'])
        print_separator()
        print("✨ Interactive SRS generation example completed successfully!")
        print("\n📄 Check example_srs.md for the generated document.")
    else:
        print("\n⚠️  Session did not complete. Try continuing the conversation.")
    
    print_separator()


if __name__ == "__main__":
    try:
        main()
    except requests.exceptions.ConnectionError:
        print("\n❌ Error: Could not connect to the SRS Generator API.")
        print("Make sure the server is running at http://localhost:5000")
        print("\nTo start the server:")
        print("  docker-compose up")
        print("  # or")
        print("  ./run.sh")
    except KeyboardInterrupt:
        print("\n\n👋 Example interrupted by user.")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
